version: '3'
services:
  RabbitMQ:
    image: "rabbitmq"
    expose:
      - "5672"
  mail_sender:
    build:
      context: mail_sender
      dockerfile: Dockerfile
    restart: always
    ports:
      - "587:587"
    depends_on:
      - RabbitMQ
    links:
      - RabbitMQ
  flask_app:
    build:
      context: flask_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - RabbitMQ
    links:
      - RabbitMQ
     